spring.application.name=WebApp

#Our databses name will be: tunetribedb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tunetribedb
spring.datasource.username=root
spring.datasource.password=

#Display DB queries in console
spring.jpa.show-sql=true 

#updates the database anytime a model is updated
spring.jpa.hibernate.ddl-auto=update
